### PR TITLE
Hesa fix 252

### PR DESCRIPTION
**Pull request by hesa**
Updated documentation how to extend the matrix

close #255

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
Please fix the commit messages and add the missing license info (SPDX headers) to the new file

**Review by priv-kweihmann — CHANGES_REQUESTED** [review]
the doc itself lgtm - but the CI pipelines have to pass for this to be merged

**Comment by priv-kweihmann** [comment]
> Updated documentation how to extend the matrix
> 
> close #255

The keyword is `Closes #255`  here - close is not caught by the Github code

**Comment by hesa** [comment]
Yeah. I know :(
Was more a hint to you guys

**Pull request closed without merging**
