### PR TITLE
Pyification

### PR DESCRIPTION
**Pull request by jens-erdmann**
Convert c style joins to python joins.
Simplify display_compatibility function.

See commits for details.

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
`Simplyfiy` in first commit message wants to become `Simplify` - apart from that I'm fine with the proposed changes

**Comment by jens-erdmann** [comment]
> `Simplyfiy` in first commit message wants to become `Simplify` - apart from that I'm fine with the proposed changes

I removed that one for now until I understand the errors in test. Seems like I am breaking stuff by oversimplifying. :sweat_smile:

**Comment by jens-erdmann** [comment]
depends on #151

**Review by priv-kweihmann — APPROVED** [review]
Not a hundred percent sure if that needs some additional test coverage - but changes lgtm

**Comment by jens-erdmann** [comment]
> Not a hundred percent sure if that needs some additional test coverage - but changes lgtm

The markdown stuff is covered as I learned by failing a test.

**Pull request merged**
