### PR TITLE
Move Makefile away from top dir

### LINKED ISSUE #91: Do you really need a Makefile with a python package?
There are not a lot of python packages in Debian that use a Makefile to run tests. Though I've only looked at three or four, I can't seem to find one. Is this a "pythonic" approach to use a Makefile for tests? I see a different approach in Debian that has the power to declare separate dependencies for tests as well.

### PR DESCRIPTION
**Pull request by hesa**
The Makefile is only for devel purposes so move it to not give the
impression that you can make && make install kind of things

Closes #91

### CODE REVIEW

**Review by priv-kweihmann — APPROVED** [review]

**Comment by jens-erdmann** [comment]
I am confused. Isn't this missing the part where it is removed in the top dir?

**Comment by hesa** [comment]
How is this possible?
cloned, fetched, git rm, push ...

**Comment by priv-kweihmann** [comment]
And now pls squash the commit and give it a reasonable commit message. `removing Makefile, copied the devel` is a red flag

**Comment by jens-erdmann** [comment]
> How is this possible? cloned, fetched, git rm, push ...

And you have committed the change? To me this looks still like just a new file.
There is a `git mv` command though...

**Comment by hesa** [comment]
I did a `git mv`...

**Comment by hesa** [comment]
redoing ... closing

**Pull request closed without merging**
